# Generated by Django 2.2.4 on 2020-03-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200328_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Outcome'),
        ),
    ]
