# Generated by Django 2.2.4 on 2020-03-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200328_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcome',
            options={'ordering': ['description']},
        ),
        migrations.AlterField(
            model_name='outcome',
            name='description',
            field=models.CharField(max_length=70),
        ),
    ]
